# 异常处理

## 异常定义

> - Java中程序执行中发生不正常的情况叫做异常，开发过程中的语法错误和逻辑错误不是异常。
> - Error：JVM无法解决的问题，如JVM内部错误，资源耗尽等，OutOfMemoryError、StackOverFlowError
> - Exception：因程序问题或者外部因素导致的一般性问题，可以使用针对性代码进行处理。如：空指针、数组越界等

## 分类

> - 受检异常：不是非受检查异常的就是受检异常
> - 非受检异常：Error和RuntimeException

<img src="https://raw.githubusercontent.com/pitything/images/main/https://cdn.jsdelivr.net/gh/pitything/images@master/image-20220702141313302.png" alt="image-20220702141313302" style="zoom:100%;" />

>- **运行时异常**：
>  - 是指编译器不要求强制处置的异常。一般是指编程时的逻辑错误，是程序员应该积极避免其出现的异常。**java.lang.RuntimeException**类及它的子类都是运行时异常。
>  - 对于这类异常，可以不作处理，因为这类异常很普遍，若全处理可能会对程序的可读性和运行效率产生影响。
>- **编译时异常**
>  - 是指编译器要求必须处置的异常。即程序在运行时由于外界因素造成的一般性异常。编译器要求Java程序必须捕获或声明所有编译时异常。
>  - 对于这类异常，如果程序不处理，可能会带来意想不到的结果。

## 异常处理机制

### try- catch-finally

```java
try{
  // 可能产生异常的代码
  int a = 1 / 0;
  return 1;
}catch (ArithmeticException exception){
  // 发生异常后的处理语句
  System.out.println(exception.getMessage());
    return 2;
}catch (Exception exception){
  // 发生异常后的处理语句
  System.out.println(exception.getMessage());
    return 3;
}finally {
  // 无论是否发生异常都会执行的语句，不论在try代码块中是否发生了异常事件，catch语句是否执行，catch语句是否有异常，catch语句中是否有return，finally块中的语句都会被执行。
  System.out.println("finally...");
  // 不要在finally中使用return
    return 4;
}
```

> exception的常用方法：
>
> - getMessage() 获取异常信息，返回字符串
> - printStackTrace() 获取异常类名和异常信息，以及异常出现在程序中的位置。返回值void。

### throws声明抛出异常

> 不确定如何处理，则使用throws声明抛出异常，由方法的调用者来进行处理。

```java
public int test1() throws Exception{
  return 0;
}
```

## 手动抛出异常

> - 使用throw关键字手动抛出异常
> - 抛出的异常类实例必须继承了 **Throwable** 或其子类，否则会有语法错误

```java
public int test2() throws Exception {
  throw new Exception("test2.....");
}
```

## 用户自定义异常类

> - 一般自定义异常都是 **RuntimeException** 的子类
> - 提供一个serialVersionUID序列号
> - 自定义异常最重要的是异常类的名字，当异常出现时，可以根据名字判断异常类型。

```java
class MyException extends RuntimeException{
    MyException(){}
    MyException(String message){
        super(message);
    }
}
```

